import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import fs from "fs";
import path from "path";

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// --- CONFIGURATION ---
// Note: Double backslashes are required for Windows paths in strings
const vaultPluginDir = "C:\\Users\\Ronny\\Documents\\Obsidian\\Orsia\\.obsidian\\plugins\\wiki-summary-normalised";

const prod = (process.argv[2] === "production");

// Helper to copy manifest.json and styles.css
function copyStaticFiles() {
	try {
		if (!fs.existsSync(vaultPluginDir)) {
			fs.mkdirSync(vaultPluginDir, { recursive: true });
		}

		fs.copyFileSync("manifest.json", path.join(vaultPluginDir, "manifest.json"));

		if (fs.existsSync("styles.css")) {
			fs.copyFileSync("styles.css", path.join(vaultPluginDir, "styles.css"));
		}

		console.log(`[Copied] manifest.json & styles.css -> ${vaultPluginDir}`);
	} catch (e) {
		console.error("[Error] Failed to copy static files:", e);
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	// CHANGE: Output directly to the vault folder
	outfile: path.join(vaultPluginDir, "main.js"),
	minify: prod,
});

if (prod) {
	await context.rebuild();
	copyStaticFiles();
	process.exit(0);
} else {
	await context.watch();
	copyStaticFiles();
	console.log(`[Watch] Watching for changes. Output: ${vaultPluginDir}`);
}
